In [1]:
# introduction.
import numpy
print numpy.__version__

1.12.1


In [14]:
# 2.1.1 creation.
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

print 'b:', b
print 'c:', c

# tuple.

print a.shape, b.shape, c.shape

# a shape attribute has only one, so it is a one-d array.

# The 0th axis and 1th axis.
c.shape = 4, 3
print 'c:', c

# -1 automatically compute axis length
c.shape = (2, -1)
print 'c:', c

d = a.reshape(2, 2)
print 'd:', d

a[1] = 100
print 'd', d

b: [5 6 7 8]
c: [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
(4,) (4,) (3, 4)
c: [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]
c: [[ 1  2  3  4  4  5]
 [ 6  7  7  8  9 10]]
d: [[1 2]
 [3 4]]
d [[  1 100]
 [  3   4]]


In [77]:
# 2.1.2 element type
import numpy as np

c = np.array([1, 2, 3, 4])
print c.dtype

ai32 = np.array([1, 2, 3, 4], dtype=np.int32)
af = np.array([1, 2, 3, 4], dtype=float)
ac = np.array([1, 2, 3, 4], dtype=complex)

print ai32.dtype, af.dtype, ac.dtype

# float and complex are internal type and np.int32 is numpy type.
# np.float64 = float
# np [float16, float32, float64, float128]

# all types.
#set(np.typeDict.values())
# np.complex = complex128

print [key for key, value in np.typeDict.items() if value is np.float64]

# print ai32.dtype.type
# print ai32.dtype
# ai32.dtype = 'f8'
# print ai32.dtype

# a = np.int16(200)
# print a*a

# v1 = 3.14
# v2 = np.float64(v1)

# %timeit v1*v1
# %timeit v2*v2

# difference of reshape dtype and astype
# t1 = np.array([1, 2, 3, 4], dtype=np.float)
# t2 = np.array([1, 2, 3, 4], dtype=np.complex)

# t3 = t1.astype(np.int32)
# t4 = t2.astype(np.complex64)

a = np.array([1], dtype=np.float)
print a.dtype


int64
int32 float64 complex128
[12, 'd', 'float64', 'float_', 'float', 'f8', 'double', 'Float64']
float64


In [86]:
# 2.1.3 automaticaly generate array.
import numpy as np

# [1, 2, 3, 4] sequence object
# print np.arange(0, 1, 0.1)
# print np.linspace(0, 1, 10)
# print np.linspace(0, 1, 10, endpoint=False)

# print np.logspace(0, 2, 5)

# print np.logspace(0, 1, 12, base=2, endpoint=False)

# np.empty((2, 3), np.int)
# np.zeros(4, np.int)

# np.full((3, 4), np.pi)
# np.ones((3, 4), np.int)

# a = np.empty((2, 4), np.int)
# np.ones_like(a)
# np.ones(a.shape, a.dtype)

s = "abcdefgh"
np.fromstring(s, dtype=np.int8)

#print 98*256 + 97
np.fromstring(s, dtype=np.int16)
np.fromstring(s, dtype=np.float)

buf = np.frombuffer(s, dtype=np.int16)
# buf[1] = 16

def func(i, j):
    return i % 4 + 1

np.fromfunction(func, (10,2))

def func2(i, j):
    return (i + 1) * (j + 1)

np.fromfunction(func2, (9, 9))


array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.],
       [  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.],
       [  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.],
       [  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.],
       [  7.,  14.,  21.,  28.,  35.,  42.,  49.,  56.,  63.],
       [  8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,  72.],
       [  9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.]])

In [155]:
# 2.1.4 access elements
import numpy as np
import random


# a = np.arange(10)
# a[5]
# a[3:5]
# a[3:-2]
# a[1:-1:2]
# a[::-1]
# a[5:1:-2]

# a[2:4] = 100, 101
# a
# b = a[3:7]
# b[2] = -10
# a

# x = np.arange(10, 1, -1)
# print x

# a = x[[3, 3, 1, 8]]
# b = x[[3, 3, -3, 8]]

# b[2] = 100
# x

# x[[3, 5, 1]] = -1, -2, -3
# x

# x = np.arange(10, 1, -1)
# x[np.array([[3, 3, 1, 8], [3, 3, -3, 8]])]

# x[[3, 3, 1, 8, 3, 3, -3, 8]].reshape(2, 4)

# x = np.arange(5, 0, -1)

# y = x[np.array([True, False, True, True, False])]
# y[0] = -3
# b = y
# b [1] = 100
# y

x = np.random.randint(0, 10, 6)
x[x > 5]

array([6, 7])

In [194]:
# 2.1.5 multi-array.
import numpy as np

def func(i, j):
    return i * 10 + j
a = np.fromfunction(func, (6, 6))
a[0, 3:5]
# a[4:, 4:]
# a[:, 2]
# a[2::2, ::2]

# x = 1
# y = 2
# x, y = y, x
# x, y

# a = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
# a

b = a[0, 3:5]
b[0] = -b[0]
a

idx = slice(None, None, 2), slice(2, None)
a[idx][idx]
a[idx]
a[:, 2]
a[slice(None), 2]

#Index expression
np.s_[::2, 2:]

a[(0, 1, 2, 3), (1, 2, 3, 4)]
a[3:, [0, 2, 5]]

mask = np.array([1, 0, 1, 0, 0, 1], dtype=np.bool)
a[mask, 2]

mask1 = np.array([1, 0, 1, 0, 0, 1])
mask2 = [True, False, True, False, False, True]

a[mask2, 2]
a[[1, 2], :]
a[[[1, 2]]]

x = np.array([[0,1], [2,3]])
y = np.array([[-1, -2], [-3,-4]])
a[x,y]

a[(0, 1, 2, 3), (-1, -2, -3, -4)].reshape(2, 2)

a[x]

palette = np.array([
    [0, 0, 0],
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255],
    [255, 255, 255]
])

image = np.array([[0, 1, 2, 0],
                [0, 3, 4, 0]])

palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [233]:
# 2.1.6 structure array
import numpy as np

persontype = np.dtype({
    'names': ['name', 'age', 'weight'],
    'formats': ['S30', 'i', 'f']}, align = True)

a = np.array([("Zhang", 32, 75.5), ("Wang", 24, 65.2)], dtype=persontype)

# S30 30 bypes char, f = np.float32, i = np.int32

a.dtype

a[0].dtype
a[0]["name"]

c = a[1]
c["name"] = "Li"
a
b=a["name"]
b

#print a[0]["age"]
#a.tostring()
#a.tofile("test.bin")

np.dtype([('f1', [('f2', np.int16)])])

np.dtype([('f0', 'i4'), ('f1', 'f8', (2, 3))])

# a = np.dtype({'surname':('S35', 0), 'age':(np.uint8, 25)})

# a = np.array(([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), dtype=np.float32)
# a.strides
# b= a[::2, ::2]
# b.strides



  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [245]:
# 2.1.7 memory structure.
import numpy as np

# a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]], dtype=np.float32)
# a.strides

# a.flags
# b = a[::2, ::2]
# a.T.flags

a = np.array([[0, 1], [2, 3], [4, 5]], dtype=np.float32)

b = a.view(np.uint32)
c = a.view(np.uint8)
a[0][0] = 3.14
print b
print c


[[1078523331 1065353216]
 [1073741824 1077936128]
 [1082130432 1084227584]]
[[195 245  72  64   0   0 128  63]
 [  0   0   0  64   0   0  64  64]
 [  0   0 128  64   0   0 160  64]]


In [262]:
%%file q_rsqrt.c

#include <stdio.h>

float Q_rsqrt(float number) {
    long i;
    float x2, y;
    float threehalfs = 1.5f;
    
    x2 = number * 0.5f;
    y = number;
    i = *(long*)&y;
    i = 0x5f3759df - (i >> 1);
    y = *(float*)&i;
    y = y*(threehalfs - (x2*y*y));
    return y;
}

int main() {
    printf("%f\n", Q_rsqrt(2.0f));
    return 0;
}

Overwriting q_rsqrt.c


In [263]:
!gcc q_rsqrt.c -o q_rsqrt

In [265]:
!./q_rsqrt

0.706930


In [280]:
import numpy as np

number = np.linspace(0.1, 10, 100)
number.dtype
y = number.astype(np.float32)
x2 = y * 0.5
i = y.view(np.int32)
i[:] = 0x5f3759df - (i >> 1)
y = y * (1.5 - x2 * y * y)
np.max(np.abs(1/np.sqrt(number) - y))

from numpy.lib.stride_tricks import as_strided
a = np.arange(6)
b = as_strided(a, shape=(4, 3), strides=(8, 8))
a[2] = 20
b


array([[ 0,  1, 20],
       [ 1, 20,  3],
       [20,  3,  4],
       [ 3,  4,  5]])