In [10]:
# 2.2 introduction

import numpy as np

x = np.linspace(0, 2*np.pi, 10)
t = np.sin(x, out=x)
t is x
x

import math

x = [i * 0.001 for i in xrange(1000000)]

def sin_math(x):
    for i, t in enumerate(x):
        x[i] = math.sin(t)
        
def sin_numpy(x):
    np.sin(x, x)
    
def sin_numpy_loop(x):
    for i, t in enumerate(x):
        x[i] = np.sin(t)
        
# #xl = x[:]
# %time sin_math(x)
# xa = np.array(x)
# %time sin_numpy(xa)

# #xl = x[:]
# %time sin_numpy_loop(x)

a = np.arange(6.0).reshape(2, 3)
print a.item(1, 2), type(a.item(1, 2)), type(a[1, 2])


5.0 <type 'float'> <type 'numpy.float64'>


In [24]:
# 2.2.1 Four Arithmetic Operation
import numpy as np

a = np.arange(0, 4)
b = np.arange(1, 5)
# print 'a;', a
# print 'b:', b
# y = a + b
y = np.arange(4)
np.add(a, b, y)
y

a; [0 1 2 3]
b: [1 2 3 4]


array([ True, False, False], dtype=bool)

In [35]:
# 2.2.2 Comparsion and bool operation

# add subtract multiply divide true_divide floor_divide negative power remainder mod

np.array([1, 2, 3]) < np.array([3, 2, 1])

# equal not_equal less less_equal greater greater_equal

# and or not
# np.logical_and np.logical_or np.logical_not np.logical_xor

a = np.arange(5)
b = np.arange(4, -1, -1)
print a == b
print a > b
print np.logical_or (a==b, a > b)
print a >= b 

np.any(a == b) and np.all(a > b)

(a == b) | (a > b)

~ np.arange(5)
~ np.arange(5, dtype=np.uint8)

[False False  True False False]
[False False False  True  True]
[False False  True  True  True]
[False False  True  True  True]


array([255, 254, 253, 252, 251], dtype=uint8)

In [46]:
# 2.2.3 self-defination universal function.

import numpy as np

def triangle_wave(x, c, c0, hc):
    x = x - int(x)
    if x >= c: r = 0.0
    elif x < c0: r = x / c0 * hc
    else: r = (c-x) / (c-c0) * hc
    return r

x = np.linspace(0, 2, 1000)
y1 = np.array([triangle_wave(t, 0.6, 0.4, 1.0) for t in x])

triangle_ufunc1 = np.frompyfunc(triangle_wave, 4, 1)
y2 = triangle_ufunc1(x, 0.6, 0.4, 1.0)
y2.dtype
y2.astype(np.float).dtype

triangle_ufunc2 = np.vectorize(triangle_wave, otypes=[np.float])
y3 = triangle_ufunc2(x, 0.6, 0.4, 1.0)
y3
np.all(y1 == y2) and np.all(y2 == y3)


True

In [77]:
# 2.2.4 broadcase
import numpy as np

a = np.arange(0, 60, 10).reshape(-1, 1)
a
a.shape
b = np.arange(0, 5)
b
b.shape
c = a + b
c
b.shape = 1, 5
b.shape
b = b.repeat(6, axis = 0)
b
a = a.repeat(5, axis=1)
a
# x, y = np.ogrid[:5, :5]
# x
# y
# x, y = np.mgrid[:5, :5]
# x
# y
x, y = np.ogrid[:1:4j, :1:3j]
x
y

x, y = np.ogrid[-2:2:20j, -2:2:20j]
z = x*np.exp(-x**2 - y**2)

a = np.arange(4)
a[None, :]
a[:, None]

x = np.array([0, 1, 4, 10])
y = np.array([2, 3, 8])
x[None, :] + y[:, None]

gy, gx = np.ix_(y, x)
gy
gx+gy

array([[ 2,  3,  6, 12],
       [ 3,  4,  7, 13],
       [ 8,  9, 12, 18]])

In [94]:
# ufunc method
import numpy as np

r1 = np.add.reduce([1, 2, 3])
r1
r2 = np.add.reduce([[1, 2, 3], [4, 5, 6]], axis=1)
r2

a1 = np.add.accumulate([1, 2, 3])
a1
a2 = np.add.accumulate([[1, 2, 3], [4, 5, 6]], axis=1)
a2

a = np.array([1, 2, 3, 4])
result = np.add.reduceat(a, indices=[0, 1, 0, 2, 0, 3, 0])
result

result[1::2]
np.add.accumulate(a)
result[::2]

np.multiply.outer([1, 2, 3, 4, 5], [2, 3, 4])

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16],
       [10, 15, 20]])